// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretBot.DataAccess;

#nullable disable

namespace SecretBot.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221024185542_Puuid")]
    partial class Puuid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SecretBot.DataAccess.Models.LolUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LolPuuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LolUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LolUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
